channels:
- defaults
dependencies:
- python=3.10.0
- pip
- pip:
  - jax==0.4.20
  - gym==0.26.2
  - hydra-core==1.3.2
  - matplotlib==3.8.1
  - optax==0.1.7
  - requests==2.31.0
  - scikit-learn==1.3.2
name: non_synap
