defaults:
  - /metric@accuracy: accuracy
  - /metric@return_average: average
  - /metric@context_accuracy: context_accuracy
  - _self_
return_average:
  key: loss
accuracy:
  from_logits: true
context_accuracy:
  from_logits: true
  context_id: ${task_id}