func: hmem
hyper_params:
  store_func: relu
  recall_func: relu
  memory_size: 200
  hebbian_type: reversed_oja
  hebbian_params:
    h_max: 1.0
    gamma_pos: 0.01
    gamma_neg: 0.01
  is_eprop: true
  is_diagonal: true
  is_fact_agnostic: true
  is_reccurrent: false